#!/bin/sh
set -e

if [ -z "${PHP_SRC_DIR}" ]; then
    echo "Please set PHP_SRC_DIR"
    exit 1
fi
if [ -z "${PHP_INSTALL_DIR}" ]; then
    echo "Please set PHP_INSTALL_DIR"
    exit 1
fi

phpVersion=master
srcDir=${PHP_SRC_DIR}/${phpVersion}
installDir=${PHP_INSTALL_DIR}/${phpVersion}

cd ${srcDir}
git pull --rebase
./buildconf --force

sharedConfig="
    --enable-option-checking=fatal \
    --enable-cgi \
    --enable-embed \
    --enable-fpm \
    --enable-ftp \
    --enable-mbstring \
    --enable-opcache \
    --enable-phpdbg \
    --enable-sockets \
    --with-curl \
    --with-fpm-user=www-data \
    --with-fpm-group=www-data \
    --with-libedit \
    --with-mhash \
    --with-mysqli=mysqlnd \
    --with-openssl \
    --with-pdo-mysql=mysqlnd \
    --with-pdo-pgsql \
    --with-pdo-sqlite \
    --with-pear \
    --with-readline \
    --with-zip \
    --with-zlib
"

# ASan + debug build
./configure \
    ${sharedConfig} \
    --enable-debug \
    --enable-zts \
    --prefix=${installDir}-debug-asan \
    --with-config-file-path=${installDir}-debug-asan \
    --with-config-file-scan-dir=${installDir}-debug-asan/conf.d \
    CFLAGS='-fsanitize=undefined,address -DZEND_TRACK_ARENA_ALLOC' \
    LDFLAGS='-fsanitize=undefined,address'
make clean
make -j "$((`nproc`+1))"
make install

make clean

switch-php ${phpVersion}-debug-asan
