#!/bin/sh
set -e

phpVersion=$1

if [ -z "${phpVersion}" ]; then
    echo "Please specify a PHP version"
    exit 1
fi

# TODO Validate build name before linking

sudo ln -sf /opt/php/${phpVersion}/bin/pear /usr/local/bin/pear
sudo ln -sf /opt/php/${phpVersion}/bin/pecl /usr/local/bin/pecl
sudo ln -sf /opt/php/${phpVersion}/bin/phar.phar /usr/local/bin/phar
sudo ln -sf /opt/php/${phpVersion}/bin/php /usr/local/bin/php
sudo ln -sf /opt/php/${phpVersion}/bin/php-cgi /usr/local/bin/php-cgi
sudo ln -sf /opt/php/${phpVersion}/bin/php-config /usr/local/bin/php-config
sudo ln -sf /opt/php/${phpVersion}/bin/phpdbg /usr/local/bin/phpdbg
sudo ln -sf /opt/php/${phpVersion}/bin/phpize /usr/local/bin/phpize
sudo ln -sf /opt/php/${phpVersion}/sbin/php-fpm /usr/local/bin/php-fpm
